server
  port:8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/Dev-Daniel-Caso/microservicios-testing.git
          search-paths: config-data
  application:
    name: config-service